"""Тесты эвристического поиска интерактивных элементов
(app/scraper/element_finder.py).

Цель — проверить scoring system на разнообразных кнопках, которые
встречаются на реальных интернет-магазинах: русские, английские,
с aria-label, с data-action, с классами BEM, с авто-сгенерированными
CSS-in-JS классами, с anti-pattern'ами («в избранное», «wishlist»).
"""

from app.scraper.element_finder import (
    MIN_CONFIDENT_SCORE,
    build_selector,
    find_best,
    find_candidates,
    _looks_autogenerated,
)
from bs4 import BeautifulSoup


# ─── Базовые сценарии ────────────────────────────────────────────────────────


def test_finds_obvious_russian_button():
    """Кнопка <button>В корзину</button> с явным классом должна найтись с большим score."""
    html = """
    <html><body>
      <button class="add-to-cart-btn" data-action="add-to-cart">В корзину</button>
    </body></html>
    """
    best = find_best(html, "add_to_cart")
    assert best is not None
    assert best.score >= MIN_CONFIDENT_SCORE
    assert "В корзину" in best.text or "корзину" in best.text.lower()


def test_finds_english_button():
    """Английская кнопка 'Add to cart' через aria-label на button."""
    html = """
    <html><body>
      <button class="product-buy-button" aria-label="Add to cart">
        <img src="x.jpg" alt="Cart">
      </button>
    </body></html>
    """
    best = find_best(html, "add_to_cart")
    assert best is not None
    assert best.score >= MIN_CONFIDENT_SCORE


def test_ignores_wishlist_button():
    """«В избранное» / Add to wishlist не должны побеждать."""
    html = """
    <html><body>
      <button class="wishlist-add">Add to wishlist</button>
      <button class="add-to-cart-btn">В корзину</button>
    </body></html>
    """
    best = find_best(html, "add_to_cart")
    assert best is not None
    assert "корзин" in best.text.lower()
    assert "wishlist" not in best.text.lower()


def test_no_button_returns_none():
    """Страница без подходящей кнопки — None."""
    html = """
    <html><body>
      <h1>Просто статья</h1>
      <p>Никаких кнопок тут нет</p>
      <a href="/about">О нас</a>
    </body></html>
    """
    assert find_best(html, "add_to_cart") is None


def test_disabled_button_low_score():
    """Disabled-кнопка должна сильно проседать в score."""
    html = """
    <html><body>
      <button class="add-to-cart" disabled>В корзину</button>
      <button class="add-to-cart-active">В корзину</button>
    </body></html>
    """
    candidates = find_candidates(html, "add_to_cart", limit=5)
    disabled_score = next(c.score for c in candidates if "disabled" in " ".join(c.explanation).lower() or any("disabled" in e for e in c.explanation))
    active_score = next(c.score for c in candidates if not any("disabled" in e for e in c.explanation))
    assert active_score > disabled_score


# ─── Многоязычность ──────────────────────────────────────────────────────────


def test_french_button():
    html = '<html><body><button class="cart">Ajouter au panier</button></body></html>'
    best = find_best(html, "add_to_cart")
    assert best is not None


def test_german_button():
    html = '<html><body><button class="cart">In den Warenkorb</button></body></html>'
    best = find_best(html, "add_to_cart")
    assert best is not None


# ─── Намерения ───────────────────────────────────────────────────────────────


def test_buy_now_intent():
    html = """
    <html><body>
      <button class="checkout-btn">Proceed to checkout</button>
      <button class="cart-add">В корзину</button>
    </body></html>
    """
    best_buy = find_best(html, "buy_now")
    assert best_buy is not None
    assert "checkout" in best_buy.text.lower() or "checkout" in best_buy.selector.lower()


def test_open_product_intent():
    html = """
    <html><body>
      <a class="product-link" href="/p/123">Подробнее</a>
    </body></html>
    """
    best = find_best(html, "open_product")
    assert best is not None
    assert "подробнее" in best.text.lower()


# ─── build_selector ──────────────────────────────────────────────────────────


def test_build_selector_uses_id():
    soup = BeautifulSoup('<button id="addToCart">Buy</button>', "lxml")
    sel = build_selector(soup.find("button"))
    assert sel == "#addToCart"


def test_build_selector_skips_autogen_class():
    """Auto-generated класс типа css-1a2b3c должен игнорироваться."""
    soup = BeautifulSoup(
        '<button class="css-1a2b3c real-class">Buy</button>', "lxml"
    )
    sel = build_selector(soup.find("button"))
    assert "css-1a2b3c" not in sel
    assert "real-class" in sel


def test_build_selector_uses_data_testid():
    """data-testid имеет приоритет если нет нормального id."""
    soup = BeautifulSoup(
        '<button data-testid="cart-add-btn">Buy</button>', "lxml"
    )
    sel = build_selector(soup.find("button"))
    assert "data-testid" in sel
    assert "cart-add-btn" in sel


def test_build_selector_input_uses_name():
    soup = BeautifulSoup(
        '<input type="submit" name="add_to_cart" value="Add">', "lxml"
    )
    sel = build_selector(soup.find("input"))
    assert sel == 'input[name="add_to_cart"]'


# ─── _looks_autogenerated ────────────────────────────────────────────────────


def test_autogen_css_in_js():
    assert _looks_autogenerated("css-1a2b3c") is True
    assert _looks_autogenerated("sc-aBcD1") is True
    assert _looks_autogenerated("jsx-1234567890") is True
    assert _looks_autogenerated("MuiButton-root-12345") is True
    assert _looks_autogenerated("") is True


def test_autogen_keeps_normal_classes():
    assert _looks_autogenerated("add-to-cart") is False
    assert _looks_autogenerated("product-buy-button") is False
    assert _looks_autogenerated("btn-primary") is False
    assert _looks_autogenerated("hero__title") is False


# ─── Сложные случаи ──────────────────────────────────────────────────────────


def test_button_inside_form():
    """Кнопка submit внутри формы добавления в корзину."""
    html = """
    <html><body>
      <form action="/cart" method="post">
        <input type="hidden" name="product_id" value="42">
        <input type="submit" name="add_to_cart" value="В корзину">
      </form>
    </body></html>
    """
    best = find_best(html, "add_to_cart")
    assert best is not None
    assert best.tag_name == "input"


def test_div_with_role_button():
    """div с role=button и явным data-action."""
    html = """
    <html><body>
      <div role="button" data-action="add-to-cart" class="cart-btn">В корзину</div>
    </body></html>
    """
    best = find_best(html, "add_to_cart")
    assert best is not None


def test_button_with_only_image_and_aria():
    """Кнопка вообще без текста, только иконка + aria-label."""
    html = """
    <html><body>
      <button aria-label="Add to cart" class="icon-cart">
        <svg></svg>
      </button>
    </body></html>
    """
    best = find_best(html, "add_to_cart")
    assert best is not None


def test_invalid_intent_raises():
    """Несуществующее намерение → ValueError."""
    import pytest
    with pytest.raises(ValueError):
        find_candidates("<html></html>", intent="frobnicate")


def test_candidates_sorted_by_score():
    """Возвращаемые кандидаты должны быть отсортированы по убыванию score."""
    html = """
    <html><body>
      <button class="buy">Купить</button>
      <button class="add-to-cart-btn" data-action="add-to-cart">В корзину</button>
      <button>Show more</button>
    </body></html>
    """
    candidates = find_candidates(html, "add_to_cart", limit=5)
    assert len(candidates) >= 2
    scores = [c.score for c in candidates]
    assert scores == sorted(scores, reverse=True)
